# Generated by Django 3.2.13 on 2023-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남', '남성'), ('여', '여성')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(max_length=10),
        ),
    ]
