# Generated by Django 3.2.13 on 2023-05-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='sub_user',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentproducts',
            name='sub_user',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
